### ISSUE TITLE
GCC errors on WIndows

### ISSUE THREAD

**Issue by SCKelemen** [nelsam/vidar#85] opened 2017-05-12 15:20 UTC
```
C:\Go\src\github.com\nelsam\vidar>go run main.go
warning: GOPATH set to GOROOT (C:\Go\) has no effect
# github.com/go-gl/glfw/v3.2/glfw
realgcc.exe: no input files
# github.com/go-gl/gl/v2.1/gl
realgcc.exe: no input files
```

**Comment by SCKelemen** [comment] 2017-05-12 16:13
fyi, my goal is to take over gxui and write a markup language for it. I just can't get /google/gxui nor /nelsam/gxui to build. If I can get them to build, and display a window, I can handle the rest. Would you mind helping me figure out how to do so?

**Comment by nelsam** [comment] 2017-05-12 16:27
I'll do my best to help out; it looks like it's a problem that I'll actually need to dig in to, though, and I don't think I'll be able to do that until tomorrow.  Today's a work day, and my wife and I have plans to attend an event tonight.

**Comment by SCKelemen** [comment] 2017-05-12 20:17
No worries mate, I didn't mean like right now. Have fun with your wife.

**Comment by SCKelemen** [comment] 2017-05-12 20:22
after manually compiling and installing /go-gl/gl/v3.2-core and /go-gl/glfw/v3.2, it am able to get vidar to build, but it instantly is killed as well. 

```
Samuels-MBP:vidar Kelemen$ go run main.go
signal: killed
```

**Comment by nelsam** [comment] 2017-05-16 16:58
What version of Go are you using?  I know I'm using some features that require a newer version of Go, but I think the master branch builds just fine on `1.7`.  The `plugins` branch requires `1.8`, but that's not merged yet.

I'm not able to reproduce this on my system.  @Kvaz1r might have a better idea?  I only have linux computers, so I have very little experience running `vidar` on Windows or OS X.

That said, you might be able to dig into the issue a bit, yourself.  Do you know how to use [`delve`](https://github.com/derekparker/delve)?

Here's a quick summary of how I use it:

```
${GOPATH}/src/github.com/nelsam/vidar $ dlv debug
(dlv) b main.go:49
(dlv) c
> main.init.1.func1() ./main.go:49 (hits goroutine(1):1 total:1) (PC: 0xa09731)
    44:                         "Basic editing of Go code is mostly complete, but " +
    45:                         "panics still happen and can result in the loss of " +
    46:                         "unsaved work.",
    47:                 Run: func(cmd *cobra.Command, args []string) {
    48:                         files = args
=>  49:                         gl.StartDriver(uiMain)
    50:                 },
    51:         }
    52: }
    53:
    54: func main() {
(dlv) s
> github.com/nelsam/gxui/drivers/gl.StartDriver() /home/valczir/tmp/vidar/src/github.com/nelsam/gxui/drivers/gl/driver.go:39 (PC: 0x623758)
    34:         pcs  []uintptr // reusable scratch-buffer for use by runtime.Callers.
    35:         uiPC uintptr   // the program-counter of the applicationLoop function.
    36: }
    37:
    38: // StartDriver starts the gl driver with the given appRoutine.
=>  39: func StartDriver(appRoutine func(driver gxui.Driver)) {
    40:         if runtime.GOMAXPROCS(-1) < 2 {
    41:                 runtime.GOMAXPROCS(2)
    42:         }
    43:
    44:         if err := glfw.Init(gl.ContextWatcher); err != nil {
(dlv) n
> github.com/nelsam/gxui/drivers/gl.StartDriver() /home/valczir/tmp/vidar/src/github.com/nelsam/gxui/drivers/gl/driver.go:40 (PC: 0x62376f)
    35:         uiPC uintptr   // the program-counter of the applicationLoop function.
    36: }
    37:
    38: // StartDriver starts the gl driver with the given appRoutine.
    39: func StartDriver(appRoutine func(driver gxui.Driver)) {
=>  40:         if runtime.GOMAXPROCS(-1) < 2 {
    41:                 runtime.GOMAXPROCS(2)
    42:         }
    43:
    44:         if err := glfw.Init(gl.ContextWatcher); err != nil {
    45:                 panic(err)
```

I'm using shorthand commands, here, but you get the idea.  `b` is shorthand for `break`, `c` for `continue`, `s` for `step`, `n` for `next`.  `delve` has a nice help menu once you've started it.

Using this, you can set breakpoints at important lines of code, then keep hitting `c` until you get your `signal: killed` result.  That should allow you to narrow it down to a single line in the `main.go` file, at least, at which point you can start stepping into the function call(s) at that line and continue to narrow it down.

**Comment by Kvaz1r** [comment] 2017-05-16 17:49
> I'm not able to reproduce this on my system. @Kvaz1r might have a better idea?
No, I also can't reproduce this error. 

 @SCKelemen  A samples from Gxui works well?

**Comment by SCKelemen** [comment] 2017-05-20 15:21
No, I also get the same errors from the GXUI repos as well.

**Comment by SCKelemen** [comment] 2017-05-20 16:30
I was running golang 1.8 on both windows and osx. Updating to 1.8.1 fixes the issue on both systems

**Closed** 2017-05-20 21:56 UTC
